<?php $labelsData = $this->getLabelsData(); ?>
<?php $rem = $this->getLabelsRem(); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt" lang="pt">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Endere&ccedil;ador</title>
		<style type="text/css">
			.style1 {font-family: Arial, Helvetica, sans-serif; font-size: 13px;	}
			.style2 {font-family: Arial, Helvetica, sans-serif;	font-size: 10px;	}
			.style4 {font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 10px;}
			.style6 {font-family: Arial, Helvetica, sans-serif; font-size: 18px; }
		</style>
		<script type="text/javascript">
			function edit(field){
				field.onclick = null;
				var text = field.innerHTML;
				var input = '<input type="text" value="'+text+'" />';
				field.innerHTML = input;
				field.firstChild.focus();
				field.firstChild.select();
				field.firstChild.onblur = function(){
					if (field.firstChild.value == "") {
						field.firstChild.value = "&nbsp;";
					}
					field.innerHTML = field.firstChild.value;
					field.onclick = function(){edit(this);};
				}
			}
		</script>
	</head>
	<body>
		<?php $e = 1; ?>
		<?php for($p = 1; $p <= $this->getPagesCount(); $p++): ?>
		<table width="765" border="0" cellpadding="14" cellspacing="0">
			<?php for($i = 1; $i <= min(2, $this->getLabelsCount() - 4 * ($p -1) ); $i++) : ?>
			<tr>
				<?php for($j = 1; $j <= min(2, $this->getLabelsCount() - 4 * ($p - 1) - 2 * ($i - 1) ); $j++) : ?>
				<td height="<?php echo ($i % 2) ? '482' : '427' ?>" width="<?php echo ($j % 2) ? '51%' : '49%' ?>"  valign="top">
					<table width="100%" border="0">
						<tr>
							<td align="left">
								<img src="<?php echo $this->getSkinUrl('images/etiquetaendereco/destinatario_peq.gif') ?>" border="0" alt="" />
							</td>
							<td align="right">
								<img src="<?php echo $this->getSkinUrl('images/etiquetaendereco/logo_correios_peq.gif') ?>" border="0" alt="" />
							</td>
						</tr>
					</table>
					<table border="0" cellpadding="0" cellspacing="0" style="height:150px;">
						<tr>
							<td valign="top">
								<div class="style1">
									<?php if ($labelsData[$e-1]['name1']): ?>
										<span onclick="edit(this)"><?php echo $labelsData[$e-1]['name1'] ?></span><br />
									<?php endif; ?>
									<?php if ($labelsData[$e-1]['name2']): ?>
										<span onclick="edit(this)"><?php echo $labelsData[$e-1]['name2'] ?></span><br />
									<?php endif; ?>
									<?php if ($labelsData[$e-1]['fone']): ?>
										<span onclick="edit(this)">Fone: <?php echo $labelsData[$e-1]['fone'] ?></span><br />
									<?php endif; ?>
									<span onclick="edit(this)"><?php echo $labelsData[$e-1]['street'] ?>&nbsp;&nbsp;&nbsp;<?php echo $labelsData[$e-1]['num'] ?></span><br />
									<?php if ($labelsData[$e-1]['compl']): ?>
										<span onclick="edit(this)"><?php echo $labelsData[$e-1]['compl'] ?></span><br />
									<?php endif; ?>
									<?php if ($labelsData[$e-1]['bairro']): ?>
										<span onclick="edit(this)"><?php echo $labelsData[$e-1]['bairro'] ?></span><br />
									<?php endif; ?>
									<span onclick="edit(this)"><?php echo $labelsData[$e-1]['city'] ?> / <?php echo $labelsData[$e-1]['uf'] ?></span><br />
									<?php echo $labelsData[$e-1]['zipcode'] ?>									
								</div>
							</td>
						</tr>
					</table>
					<div align="center" class="style4">
						<br 
						<?php foreach ($labelsData[$e-1]['barcode'] as $code): ?>
							/><img src="<?php echo $this->getSkinUrl('images/etiquetaendereco/') . $code['type'] . '.gif' ?>" width="<?php echo $code['value'] ?>" height="90" alt="" 
						<?php endforeach ?>
						/><br />
						<?php echo $labelsData[$e-1]['zipcode'] ?>
					</div>
					<br />
					<hr align="center" size="1" width="100%" style="border: 0 none #c0c0c0; border-top: 1px solid #c0c0c0;"/>
					<div class="style2">
						<b>Remetente:</b><br />
						<?php if ($rem['name1']):?>
							<span onclick="edit(this)"><?php echo $rem['name1'] ?></span><br />
						<?php endif; ?>
						<?php if ($rem['name2']):?>
							<span onclick="edit(this)"><?php echo $rem['name2'] ?></span><br />
						<?php endif; ?>
						<?php if ($rem['fone']):?>
							<span onclick="edit(this)"><?php echo $rem['fone'] ?></span><br />
						<?php endif; ?>
						<span onclick="edit(this)"><?php echo $rem['address'] ?></span><br />
						<?php if ($rem['compl']):?>
							<span onclick="edit(this)"><?php echo $rem['compl']?></span><br />
						<?php endif; ?>
						<span onclick="edit(this)"><?php echo $rem['bairro']?></span><br />
						<span onclick="edit(this)"><?php echo $rem['zipcode']?>&nbsp;&nbsp;&nbsp;<?php echo $rem['city']?></span>					
					</div>
				</td>
				<?php if ($this->getLabelsCount() % 4 == 1 && $this->getLabelsCount() == $e): ?>
					<td height="482" width="49%"  valign="top"></td>
				<?php endif; ?>
			<?php $e++; ?>
			<?php endfor; ?>
			</tr>
		<?php endfor; ?>
		</table>
			<?php if ($p < $this->getPagesCount()): ?>
		<div style="page-break-after: always;"></div>
		<div style="margin-top: 8px;"></div>
			<?php endif; ?>
		<?php endfor; ?>
	</body>
</html>
